import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  BadgeCheck,
  BarChart3,
  BedDouble,
  Briefcase,
  Building2,
  Car,
  CloudRain,
  CloudSun,
  Compass,
  Droplets,
  Euro,
  Factory,
  FileBadge,
  Fuel,
  Globe2,
  GraduationCap,
  Handshake,
  HardHat,
  Hash,
  Heart,
  Hospital,
  Hotel,
  Landmark,
  LandPlot,
  MapPin,
  MapPinned,
  Mountain,
  Pill,
  Plane,
  Recycle,
  School,
  ScrollText,
  Ship,
  Sun,
  Thermometer,
  Trash2,
  TrendingUp,
  Umbrella,
  Users,
  Wallet,
  Waves,
  Wifi,
  Wind,
  Zap,
} from "lucide-react";

/** Icone di default per etichette KpiCard (match esatto sulla label). */
export const KPI_ICONS: Record<string, LucideIcon> = {
  Popolazione: Users,
  "Reddito medio": Euro,
  "Indice turisticità": Hotel,
  "Raccolta differenziata": Recycle,
  "Copertura FTTH": Wifi,
  "Speranza di vita": Heart,
  "Età media": Users,
  "Indice di vecchiaia": TrendingUp,
  "Indice di dipendenza": Users,
  "Tasso occupazione": Briefcase,
  "Tasso disoccupazione": Briefcase,
  "Tasso di attività": Briefcase,
  "Laureati 25–64": GraduationCap,
  "Laureati 25-64": GraduationCap,
  "Diplomati+ 25–64": GraduationCap,
  "Diplomati+ 25-64": GraduationCap,
  "Consumo di suolo": LandPlot,
  "Punti ricarica EV": Zap,
  "Punti EV": Zap,
  Veicoli: Car,
  "Immobili PA": Building2,
  "Saldo cassa SIOPE": Wallet,
  "Saldo cassa": Wallet,
  PNRR: FileBadge,
  "PNRR assegnato": FileBadge,
  "Opere BDAP": HardHat,
  "Contratti ANAC": ScrollText,
  "Enti RUNTS": Handshake,
  "Civici ANNCSU": MapPinned,
  "Impianti carburanti": Fuel,
  "Pendolarismo netto": ArrowLeftRight,
  "Elevazione media": Mountain,
  "CF / Catastale": Hash,
  Strutture: Hotel,
  Letti: BedDouble,
  Camere: BedDouble,
  "Arrivi totali": Plane,
  "Presenze totali": Users,
  "Permanenza media": BedDouble,
  "Quota stranieri": Globe2,
  Classificazione: BadgeCheck,
  "Posti barca in Toscana": Ship,
  "Coordinate porto": MapPin,
  "Unità locali": Building2,
  "Addetti totali": Briefcase,
  "UL per 1000 ab.": Building2,
  Contribuenti: Euro,
  "Uscite SIOPE": Wallet,
  "Incassi SIOPE": Wallet,
  "Superficie PA": LandPlot,
  Superficie: LandPlot,
  "Rifiuti pro capite": Trash2,
  "Zona sismica": Activity,
  "Pendenza media": Mountain,
  "Esposizione dominante": Compass,
  "% veicoli inquinanti": Factory,
  "Incidenti (ultimo anno)": AlertTriangle,
  "Benzina self media": Fuel,
  "Gasolio self media": Fuel,
  "Miglior benzina self": Fuel,
  "Miglior gasolio self": Fuel,
  Farmacie: Pill,
  Parafarmacie: Pill,
  Ospedali: Hospital,
  "Beni culturali geo": Landmark,
  "Farmacie geo": Heart,
  "Posti barca": Ship,
  "Punti ricarica EV (comune)": Zap,
  "Vento (live)": Wind,
  "Balneazione eccellente": Waves,
  Temperatura: Thermometer,
  "Umidità": Droplets,
  Pioggia: CloudRain,
  "Copertura nuvole": CloudSun,
  "Pressione": Activity,
  "UV index": Sun,
  Visibilità: Compass,
  "Punto di rugiada": Droplets,
  "Probabilità pioggia": Umbrella,
  "Maschi / Femmine": Users,
  "Diploma o oltre": GraduationCap,
  Terziario: Briefcase,
  "Unità locali ASIA": Building2,
  "Patrimonio PA": Landmark,
  "Tipo struttura": Ship,
  "Aree balneazione": Waves,
  "Classificazione eccellente": Waves,
  "Superamenti limiti 2024": AlertTriangle,
  "Stazione qualità aria": Wind,
  Percepita: Thermometer,
  "Min / Max 24h (KPI)": Thermometer,
  Vento: Wind,
  Nuvolosità: CloudSun,
  Precipitazioni: CloudRain,
  "Direzione vento": Compass,
  Plessi: School,
  "Alunni / bambini": Users,
  Infanzia: GraduationCap,
  "Cittadinanza non italiana": Globe2,
};

export const KPI_ICON_FALLBACK: LucideIcon = BarChart3;

export function resolveKpiIcon(
  label: string,
  icon?: LucideIcon,
): LucideIcon {
  if (icon) return icon;
  return KPI_ICONS[label] ?? KPI_ICON_FALLBACK;
}
